### ISSUE TITLE
Error when opening the documentation

### ISSUE THREAD

**Issue by brizaldi** [conduit-dart/conduit-site#4]
https://gitbook.theconduit.dev/

![Screenshot 2022-11-08 074649](https://user-images.githubusercontent.com/41714881/200446670-40a7dee7-da96-4864-b23f-5d53dd78637f.png)

**Comment by delphi007** [comment]
Could visit the document from here --> https://github.com/conduit-dart/conduit/blob/master/docs
However this problem should be fixed

**Comment by brizaldi** [comment]
Seems like the documentation was moved here: https://docs.theconduit.dev
